"""Regenerate paperwriting/table_rq2.tex from the corrected n=41 taxonomy.

The output is a LaTeX fragment only: no table float, caption, or label is added.

The manuscript does NOT \\input the generated file.  \\input is outside the
approved command surface enforced by src/check_manuscript.py, so the n=41 route
table is written out inline in paperwriting/manuscript/main.tex (see
\\label{tab:routes}).  Running this script therefore does not change the paper;
its output serves the supplement and acts as a machine-generated cross-check of
the inline copy.  Any census change must be applied to main.tex by hand and
re-verified with src/check_manuscript.py.

Usage:
    python src/generate_table_rq2.py
    python src/generate_table_rq2.py --results paperwriting/results.json
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
PAPER_DIR = ROOT / "paperwriting"
DELIVERY_DIR = PAPER_DIR / "delivery"


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _format_pct(value: float) -> str:
    return f"{100 * value:.1f}\\%"


def generate(results_path: Path, output_path: Path) -> None:
    with results_path.open() as handle:
        results: dict[str, Any] = json.load(handle)

    base_path = "rq2_taxonomy.p0_corrected_taxonomy"
    block = results["rq2_taxonomy"]["p0_corrected_taxonomy"]
    n = int(block["n"])
    n_facts = int(block["n_unique_facts"])
    dist = block["dist"]
    pct = block["pct"]
    agreement = block["agreement"]

    expected_dist = {
        "Bridge": 27,
        "Recall": 11,
        "Reflective-override": 3,
        "Associative": 0,
    }
    expected_pct = {
        "Bridge": 0.6585365853658537,
        "Recall": 0.2682926829268293,
        "Reflective-override": 0.07317073170731707,
        "Associative": 0.0,
    }
    expected_agreement = {
        "unanimous_cases": 35,
        "two_one_cases": 6,
        "split_1_1_1_cases": 0,
        "raw_pairwise_agreement": "111/123=.902439",
        "fleiss_kappa": 0.8125952260030472,
    }

    checks = {
        "n=41": n == 41,
        "n_unique_facts=33": n_facts == 33,
        "route_counts_match_spec": dist == expected_dist,
        "route_percentages_match_spec": all(
            math.isclose(float(pct[key]), expected_pct[key], abs_tol=1e-12)
            for key in expected_pct
        ),
        "counts_sum_to_n": sum(int(value) for value in dist.values()) == n,
        "percentages_equal_count_over_n": all(
            math.isclose(float(pct[key]), int(dist[key]) / n, abs_tol=1e-12)
            for key in dist
        ),
        "agreement_matches_spec": all(
            agreement[key] == value
            if not isinstance(value, float)
            else math.isclose(float(agreement[key]), value, abs_tol=1e-12)
            for key, value in expected_agreement.items()
        ),
        "panel_decisions_sum_to_n": (
            int(agreement["unanimous_cases"])
            + int(agreement["two_one_cases"])
            + int(agreement["split_1_1_1_cases"])
            == n
        ),
    }
    failures = [name for name, passed in checks.items() if not passed]
    if failures:
        raise RuntimeError(f"corrected-taxonomy audit failed: {failures}")

    rows = []
    for route in ["Bridge", "Recall", "Reflective-override", "Associative"]:
        rows.append(
            f"{route} & {int(dist[route])} & {_format_pct(float(pct[route]))} \\\\"
        )
    body = "\n".join(rows)
    latex = rf"""% AUTO-GENERATED by src/generate_table_rq2.py; do not edit by hand.
% Numeric source: {base_path}
% This fragment intentionally contains no table float, caption, or label.
\begingroup
\small
\setlength{{\tabcolsep}}{{4pt}}
\begin{{tabular*}}{{\columnwidth}}{{@{{\extracolsep{{\fill}}}}lrr@{{}}}}
\toprule
\multicolumn{{3}}{{c}}{{Corrected route taxonomy}} \\
\multicolumn{{3}}{{c}}{{\footnotesize $n={n}$ instances; {n_facts} unique facts}} \\
\cmidrule(lr){{1-3}}
Route & Count & Percent \\
\midrule
{body}
\bottomrule
\end{{tabular*}}
\par\vspace{{2pt}}
\parbox{{\columnwidth}}{{\footnotesize Agreement: Fleiss' $\kappa=.813$;
raw agreement $111/123=.902$; unanimous 35, 2--1: 6, split: 0.}}
\endgroup
"""
    output_path.write_text(latex)

    DELIVERY_DIR.mkdir(parents=True, exist_ok=True)
    source_map = {
        "artifact": "table_rq2",
        "numeric_source": "paperwriting/results.json",
        "status": "PASS",
        "output": str(output_path.relative_to(ROOT)),
        "output_sha256": _sha256(output_path),
        "entries": [
            {
                "json_path": f"{base_path}.n",
                "raw_value": n,
                "rendered_value": "n=41 instances",
                "status": "MATCH",
            },
            {
                "json_path": f"{base_path}.n_unique_facts",
                "raw_value": n_facts,
                "rendered_value": "33 unique facts",
                "status": "MATCH",
            },
            {
                "json_path": f"{base_path}.dist",
                "raw_value": dist,
                "rendered_value": expected_dist,
                "status": "MATCH",
            },
            {
                "json_path": f"{base_path}.pct",
                "raw_value": pct,
                "rendered_value": {
                    key: f"{100 * float(pct[key]):.1f}%" for key in pct
                },
                "status": "MATCH",
            },
            {
                "json_path": f"{base_path}.agreement.fleiss_kappa",
                "raw_value": agreement["fleiss_kappa"],
                "rendered_value": ".813",
                "display_transform": "round to 3 decimals",
                "status": "MATCH",
            },
            {
                "json_path": f"{base_path}.agreement.raw_pairwise_agreement",
                "raw_value": agreement["raw_pairwise_agreement"],
                "rendered_value": "111/123=.902",
                "display_transform": "round rate to 3 decimals",
                "status": "MATCH",
            },
            {
                "json_path": f"{base_path}.agreement",
                "raw_value": {
                    "unanimous_cases": agreement["unanimous_cases"],
                    "two_one_cases": agreement["two_one_cases"],
                    "split_1_1_1_cases": agreement["split_1_1_1_cases"],
                },
                "rendered_value": "unanimous 35; 2--1: 6; split: 0",
                "status": "MATCH",
            },
        ],
        "invariants": [
            {"name": name, "status": "PASS" if passed else "FAIL"}
            for name, passed in checks.items()
        ],
    }
    source_map_path = DELIVERY_DIR / "table_rq2_source_map.json"
    source_map_path.write_text(
        json.dumps(source_map, indent=2, ensure_ascii=False) + "\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--results",
        type=Path,
        default=PAPER_DIR / "results.json",
        help="authoritative results JSON (read only)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=PAPER_DIR / "table_rq2.tex",
        help="generated LaTeX fragment",
    )
    args = parser.parse_args()
    generate(args.results, args.output)
    print(f"generated {args.output.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
